name: reviewdog
on: [push, pull_request]

jobs:
  reviewdog_eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - name: Install eslint dependencies
        run: npm install eslint prettier eslint-plugin-prettier eslint-config-prettier -D
      - name: Run eslint with reviewdog
        uses: reviewdog/action-eslint@v1.23.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          eslint_flags: 'js/**/*.js'